# See: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Heading rules
heading-style:  # MD003 - Heading style (default: "consistent")
  style: "atx"  # Use # style headings consistently

no-duplicate-heading:  # MD024 - Multiple headings with the same content (default: siblings_only: false)
  siblings_only: true  # Only check sibling headings, allow same content at different levels

# List rules
ul-style:  # MD004 - Unordered list style (default: "consistent")
  style: "dash"  # Use - for unordered lists consistently

# Line length (default: 80 characters)
line-length:  # MD013 - Line length
  line_length: 100  # Allow longer lines for readability
  heading_line_length: 100
  code_blocks: true  # Allow longer code blocks

# Code rules
code-block-style:  # MD046 - Code block style (default: "consistent")
  style: "fenced"  # Prefer fenced code blocks over indented

code-fence-style:  # MD048 - Code fence style (default: "consistent")
  style: "backtick"  # Use ``` instead of ~~~

# Emphasis and formatting rules
emphasis-style:  # MD049 - Emphasis style (default: "consistent")
  style: "underscore"  # Use _emphasis_ instead of *emphasis*

strong-style:  # MD050 - Strong style (default: "consistent")
  style: "asterisk"  # Use **strong** instead of __strong__
